<?php
/** @var Convert_Porterbuddy_Block_Availability $this */
/** @var Mage_Core_Helper_Data $coreHelper */
$coreHelper = $this->helper('core');
?>
<script>
window.porterbuddy = {
      token: 'y3wt37LqBsiLo62Jkx284XEdi4LzdX6pihZFwqYX',
      view: 'availability'    };
    (function() {
      var link = document.createElement('link');
      link.rel = 'stylesheet';
      link.type = 'text/css';
      link.href = 'https://widget.porterbuddy-test.com/porterbuddy-widget.css';
      document.head.appendChild(link);
      var scriptEl = document.createElement('script');
      scriptEl.async = true;
      scriptEl.src = 'https://widget.porterbuddy-test.com/porterbuddy-widget.js';
      document.head.appendChild(scriptEl);
    })();
</script>
