<?php
/**
 * @author Convert Team
 * @copyright Copyright (c) 2017 Convert (http://www.convert.no/)
 */
/** @var Convert_Porterbuddy_Block_Popup $this */
?>
<div id="porterbuddy-popup" class="porterbuddy-popup" style="display: none;">
    <div class="porterbuddy-popup__header">
        <img src="<?php echo $this->getSkinUrl('images/logo_porterbuddy.svg') ?>" class="image image-logo"
             width="100" height="20" alt="<?php echo $this->escapeHtml($this->__('Porterbuddy')) ?>" />
        <h2 class="porterbuddy-popup__header__title"><?php echo $this->getTitle() ?></h2>
        <p class="porterbuddy-popup__header__description"><?php echo $this->getDescription() ?></p>
        <div id="porterbuddy-message" class="alert" style="display: none;"></div>
    </div>
    <div class="porterbuddy-popup__content">
        <div id="porterbuddy-map"></div>
        <div class="porterbuddy-popup__content__address">
            <span><?php echo $this->getAddressText() ?>:</span>
            <input type="text" id="porterbuddy-address" value="<?php echo $this->escapeHtml($this->getDeliveryAddress()) ?>" />
        </div>
    </div>
    <div class="porterbuddy-popup__footer">
        <button type="button" class="button" id="porterbuddy-save">
            <?php echo $this->__('Save') ?>
        </button>
        <button type="button" class="button" id="porterbuddy-close" style="display: none;">
            <?php echo $this->__('Close') ?>
        </button>
    </div>
</div>
<?php echo $this->getChildHtml(); ?>
