<?php
/**
 * @author Convert Team
 * @copyright Copyright (c) 2017 Convert (http://www.convert.no/)
 */
/** @var Convert_Porterbuddy_Block_Checkout $this */
$coreHelper = $this->helper('core');
?>

<script type="text/javascript">
    window.porterbuddyWidget = new PorterbuddyWidget({
        formKey: '<?php echo $this->getFormKey() ?>',
        refreshUrl: '<?php echo $this->getUrl('convert_porterbuddy/delivery/refresh') ?>',
        refreshOptionsTimeout: <?php echo json_encode($this->getRefreshOptionsTimeout()) ?>,
        optionsSaveUrl: '<?php echo $this->getUrl('convert_porterbuddy/delivery/options') ?>',
        widgetHtml: <?php echo json_encode($this->getChildHtml()) ?>,
        postcode: <?php echo json_encode($this->getPostcode()) ?>
    });
</script>
<script>
window.porterbuddy = {
      token: 'y3wt37LqBsiLo62Jkx284XEdi4LzdX6pihZFwqYX',
      view: 'checkout',
      deliveryWindows: <?php echo json_encode(Mage::getSingleton('checkout/session')->getPbWindows($options))?>,
      onSelectDeliveryWindow: function(selectedWindow){
        let code = 'cnvporterbuddy_' + selectedWindow.product + '_' + selectedWindow.start + '_' + selectedWindow.end
        let option = window.porterbuddyWidget.$porterbuddyRates.filter('[value="' + code + '"]').trigger('click', true);
      },
      onUpdateDeliveryWindows: function(callback) {

        jQuery.ajax('<?php echo $this->getUrl('convert_porterbuddy/delivery/refresh') ?>', {
            dataType: 'json'
          })
          .done(function(deliveryWindows) {
            callback(deliveryWindows);
          }
        }
    };
    (function() {
      var link = document.createElement('link');
      link.rel = 'stylesheet';
      link.type = 'text/css';
      link.href = 'https://widget.porterbuddy-test.com/porterbuddy-widget.css';
      document.head.appendChild(link);
      var scriptEl = document.createElement('script');
      scriptEl.async = true;
      scriptEl.src = 'https://widget.porterbuddy-test.com/porterbuddy-widget.js';
      document.head.appendChild(scriptEl);
    })();
</script>
