<?php
/**
 * @author Convert Team
 * @copyright Copyright (c) 2017 Convert (http://www.convert.no/)
 */
/** @var Convert_Porterbuddy_Block_Checkout $this */
?>
<li id="porterbuddy-widget" class="porterbuddy-widget porterbuddy-widget-item">
    <input name="shipping_method_porterbuddy" type="radio" value="s_method_porterbuddy" id="s_method_porterbuddy" class="radio"/>
    <label class="porterbuddy-widget-title" for="s_method_porterbuddy">
        <?php echo $this->getTitle() ?>
    </label>

    <div class="porterbuddy-widget-description carrier-method-desc">
        <?php echo $this->getDescription() ?>
    </div>

    <div id="porterbuddy-widget"></div>

</li>
