<?php
/**
 * @author Convert Team
 * @copyright Copyright (c) 2017 Convert (http://www.convert.no/)
 */
/** @var Convert_Porterbuddy_Block_Widget $this */
?>
<script type="text/javascript">
    window.porterbuddyWidget = new PorterbuddyWidget({
        formKey: '<?php echo $this->getFormKey() ?>',
        optionsSaveUrl: '<?php echo $this->getUrl('convert_porterbuddy/location/options') ?>',
        dates: <?php echo json_encode($this->getDates()) ?>,
        widgetHtml: <?php echo json_encode($this->getChildHtml()) ?>,
        timeslotTemplate: <?php echo json_encode($this->getTimeslotTemplate()) ?>
    });
</script>
