<?php
/**
 * @author Convert Team
 * @copyright Copyright (c) 2017 Convert (http://www.convert.no/)
 */
/** @var Convert_Porterbuddy_Block_Widget $this */
?>
<li id="porterbuddy-widget" class="porterbuddy-widget porterbuddy-widget-item">
    <input name="shipping_method_porterbuddy" type="radio" value="" id="s_method_porterbuddy" class="radio"/>
    <label for="s_method_porterbuddy">
        <?php echo $this->getTitle() ?>
    </label>
    <img src="<?php echo $this->getSkinUrl('images/logo_porterbuddy.svg') ?>" class="image porterbuddy-widget-logo"
         width="100" height="20" alt="<?php echo $this->escapeHtml($this->__('Porterbuddy')) ?>" />
    <div class="porterbuddy-widget-description">
        <?php echo $this->getDescription() ?>
    </div>

    <div class="porterbuddy-widget-date-selectors">
        <a href="javascript: void(0);" class="porterbuddy-widget-date-selector prev-date">
            <span><?php echo $this->__('Previous Day') ?></span>
        </a>
        <span id="selected-date" class="porterbuddy-widget-selected-date selected-date">
            <!--placeholder-->
        </span>
        <a href="javascript: void(0);" class="porterbuddy-widget-date-selector next-date">
            <span><?php echo $this->__('Next Day') ?></span>
        </a>
    </div>
    <div id="timeslots" class="porterbuddy-widget-timeslots">
        <!--placeholder -->
    </div>
    <?php if ($this->getReturnEnabled()): ?>
        <div class="porterbuddy-widget-return">
            <label>
                <input type="checkbox" value="1" id="porterbuddy_return" />
                <?php echo $this->getReturnText() ?>
            </label>
        </div>
    <?php endif; ?>
    <div class="porterbuddy-widget-leave-doorstep">
        <label>
            <input type="checkbox" value="1" id="porterbuddy_leave_doorstep"
                <?php if ($this->getLeaveDoorstep()) echo ' checked="checked"' ?> />
            <?php echo $this->getLeaveDoorstepText() ?>
        </label>
    </div>
    <div class="porterbuddy-widget-comment">
        <textarea id="porterbuddy_comment"
              placeholder="<?= $this->escapeHtml($this->getCommentText()) ?>"
              maxlength="512"><?php echo $this->escapeHtml($this->getComment()) ?></textarea>
    </div>
</li>
